"""add_product_sales_stats_table

Revision ID: 0759a3792329
Revises: add_product_supplier
Create Date: 2025-12-21 16:40:04.853191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0759a3792329'
down_revision = 'add_product_supplier'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_sales_stats',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_sales_stats', schema=None) as batch_op:
        batch_op.create_index('idx_product_date', ['product_id', 'sale_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_sales_stats_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sales_stats_sale_date'), ['sale_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sales_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_sales_stats_sale_date'))
        batch_op.drop_index(batch_op.f('ix_product_sales_stats_product_id'))
        batch_op.drop_index('idx_product_date')

    op.drop_table('product_sales_stats')
    # ### end Alembic commands ###
