"""add_draft_status_to_group_deals

Revision ID: add_draft_status
Revises: 0759a3792329
Create Date: 2026-01-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_draft_status'
down_revision = '0759a3792329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: This migration adds support for a new 'draft' status value for group_deals.status
    # Since status is stored as a VARCHAR column, no schema change is needed.
    # The 'draft' status is admin-only and won't be visible to regular users.
    # 
    # The status column already supports any string value up to 50 characters.
    # Changes are in application code:
    # - backend/constants/status_enums.py: Added GroupDealStatus.DRAFT
    # - backend/models/groupdeal.py: Changed default status to DRAFT
    # - backend/routes/products.py: Public endpoint filters out draft deals
    # - shared/status-enums.js: Frontend enum updated
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # To downgrade, revert application code changes and optionally update
    # any group_deals with status='draft' to status='upcoming'
    # 
    # SQL to manually update if needed:
    # UPDATE group_deals SET status='upcoming' WHERE status='draft';
    pass
    # ### end Alembic commands ###
