"""Add OTP tracking table

Revision ID: cf1c5204ff38
Revises: bee2dd2c8a9c
Create Date: 2025-11-16 09:40:52.071197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1c5204ff38'
down_revision = 'bee2dd2c8a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_attempts',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('twilio_status', sa.String(length=50), nullable=True),
    sa.Column('twilio_sid', sa.String(length=100), nullable=True),
    sa.Column('twilio_error_code', sa.String(length=20), nullable=True),
    sa.Column('twilio_error_message', sa.String(length=500), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_attempts_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_attempts_twilio_sid'), ['twilio_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_attempts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_otp_attempts_twilio_sid'))
        batch_op.drop_index(batch_op.f('ix_otp_attempts_phone'))
        batch_op.drop_index(batch_op.f('ix_otp_attempts_created_at'))

    op.drop_table('otp_attempts')
    # ### end Alembic commands ###
